### ISSUE TITLE
Signals not working on Android 

### ISSUE THREAD

**Issue by FantaMagier** [TelemetryDeck/FlutterSDK#12] opened 2024-07-04 18:30 UTC
Hello everyone, somehow the Android TelemtryDeck requests are not coming to the server but in the SDk everything is displayed correctly and the test mode is also switched off. The debug mode also shows the request normally. With iOS everything works and I use the latest version. The Internet permission is set on Android.

**Comment by kkostov** [comment] 2024-07-22 10:39
Hi @FantaMagier, does the issue still persist? 

If yes, would it be possible to share some logcat traces which include example events e.g. all lines prefixed with `D/TELEMETRYDECK` and the http stack.

To see the trace, you will need to activate debugging when initialising the SDK:

```dart
Telemetrydecksdk.start(
    const TelemetryManagerConfiguration(
      appID: "...",
      debug: true, <--- add this
    ),
  );
```

**Comment by FantaMagier** [comment] 2024-07-22 11:31
@kkostov Sure. Here are some logs from Android:

I/System.out( 6190): [{"receivedAt":"2024-07-12T06:40:54.052Z","appID":"APPID","clientUser":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","sessionID":"45a74dfb-a147-4c0a-9d38-6cc9cd2c5535","type":"App Start","payload":["dartVersion:3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on 'android_arm64'","telemetryClientVersion:Flutter 0.3.0","FirstOpen:false","appVersion:2.0.5","buildNumber:73","systemVersion:Android SDK: 34 (14)","majorSystemVersion:14","majorMinorSystemVersion:14.0","locale:Deutsch (Deutschland)","brand:google","targetEnvironment:emu64a","modelName:sdk_gphone64_arm64 (sdk_gphone64_arm64)","architecture:aarch64","operatingSystem:Android"],"isTestMode":"false"},{"receivedAt":"2024-07-12T06:40:54.053Z","appID":"APPID","clientUser":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","sessionID":"45a74dfb-a147-4c0a-9d38-6cc9cd2c5535","type":"Welcome Page (Onboarding V2)","payload":["dartVersion:3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on 'android_arm64'","telemetryClientVersion:Flutter 0.3.0","appVersion:2.0.5","buildNumber:73","systemVersion:Android SDK: 34 (14)","majorSystemVersion:14","majorMinorSystemVersion:14.0","locale:Deutsch (Deutschland)","brand:google","targetEnvironment:emu64a","modelName:sdk_gphone64_arm64 (sdk_gphone64_arm64)","architecture:aarch64","operatingSystem:Android"],"isTestMode":"false"},{"receivedAt":"2024-07-12T06:40:55.566Z","appID":"APPID","clientUser":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","sessionID":"45a74dfb-a147-4c0a-9d38-6cc9cd2c5535","type":"Disclaimer (Onboarding V2)","payload":["dartVersion:3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on 'android_arm64'","telemetryClientVersion:Flutter 0.3.0","appVersion:2.0.5","buildNumber:73","systemVersion:Android SDK: 34 (14)","majorSystemVersion:14","majorMinorSystemVersion:14.0","locale:Deutsch (Deutschland)","brand:google","targetEnvironment:emu64a","modelName:sdk_gphone64_arm64 (sdk_gphone64_arm64)","architecture:aarch64","operatingSystem:Android"],"isTestMode":"false"}]

I/System.out( 6190): BODY END

**Comment by kkostov** [comment] 2024-07-25 08:45
I was not able to reproduce an issue that may be causing this. I tested submitting the signals and they immediately appear in the dashboard:

<img width="1012" alt="Screenshot 2024-07-25 at 10 40 11" src="https://github.com/user-attachments/assets/afe41d97-7ecd-4fbf-b42b-d783dc6465c2">

Would it be possible to double check that:

* Internet permissions have been setup for the Android target.
* There are no network/proxy related errors logged after sending the events.

Version `0.5.0` of the SDK was recently released including a number of improvements for both iOS and Android. Perhaps trying the latest build can be of help.

**Comment by FantaMagier** [comment] 2024-07-25 12:39
I think the requests are displayed correctly in the signal types but not in the graphs etc. So TelemetryDeck is definitely receiving requests.

If I leave out the parameter testMode: false, it is always testMode: true for me.

  telemetrydecksdk: ^0.5.0


```dart
  Telemetrydecksdk.start(
    const TelemetryManagerConfiguration(
      appID: "ID",
      testMode: false,
    ),
  );

// On the Screen Opening
    Telemetrydecksdk.send(
      "ANDROID SDK TEST",
    );

```

![image](https://github.com/user-attachments/assets/35b8458d-f321-48b7-bbfc-3b2913d0b36b)

Count Signals: Nothing
![image](https://github.com/user-attachments/assets/d76b1aab-34e7-459f-99e8-812c451070f0)
Count Users: One User should be min. 2
![image](https://github.com/user-attachments/assets/843d78be-a6a1-48f4-8923-ba03599b6010)

**Comment by kkostov** [comment] 2024-07-25 15:58
@FantaMagier If `testMode` is not explicitly set, then the [KotlinSDK](https://github.com/TelemetryDeck/KotlinSDK/blob/main/lib/src/main/java/com/telemetrydeck/sdk/TelemetryManager.kt#L390) will try to guess it depending on how the app is being executed.

Currently we check for the flag `FLAT_DEBUGGABLE` in the application context ([info](https://stuff.mit.edu/afs/sipb/project/android/docs/reference/android/content/pm/ApplicationInfo.html#FLAG_DEBUGGABLE)). When the flag is present, `testMode` will be set to true. This is usually the case for non-release builds or dev/debug flavours.

**Comment by FantaMagier** [comment] 2024-07-25 16:03
@kkostov ok with the test mode then fits but it still does not explain why no signals are displayed in the diagram. These have also been forced by me testMode = false. The requests in the console also return all 200 status codes with testMode = false

**Comment by winsmith** [comment] 2024-07-26 07:16
> Count Signals: Nothing ![image](https://private-user-images.githubusercontent.com/21313268/352106954-d76b1aab-34e7-459f-99e8-812c451070f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Nzc3MzIsIm5iZiI6MTcyMTk3NzQzMiwicGF0aCI6Ii8yMTMxMzI2OC8zNTIxMDY5NTQtZDc2YjFhYWItMzRlNy00NTlmLTk5ZTgtODEyYzQ1MTA3MGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzEzYzZlNDIwOGNhMDQ3OWM1MzIwMjRiZmNiYTExZTIzZWY1NDVmNDEwNTZjMjExNjRmMDg1YWU1YTYwZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KHFRMv4LCMFo7THJ8V8EF5RyBY_sqongrgl0YVMPUtI)

Note that you have 4 signals on July 25 in this screenshot, its just badly visible because it's just one data point without a line (which is my fault)

 Count Users: One User should be min. 2 ![image](https://private-user-images.githubusercontent.com/21313268/352107020-843d78be-a6a1-48f4-8923-ba03599b6010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Nzc3MzIsIm5iZiI6MTcyMTk3NzQzMiwicGF0aCI6Ii8yMTMxMzI2OC8zNTIxMDcwMjAtODQzZDc4YmUtYTZhMS00OGY0LTg5MjMtYmEwMzU5OWI2MDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZjAzODY5MDI0ZDg4YTM2YjMwNzg2MGM1ZDBlOGI4YzMxMGM2MDQwNWRkZjA1OWMyYmZiNzA4Mzk5YmU2MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lST-Ii0MEacRxB0V3v86EeIquz04Km70ZSF8ZshXncY)

I had a Quick Look into the database and there is indeed just one distinct user identifier for this combination of clientUser and signal type. 

So there could be a problem with user identifiers here, where the user identifier either doesn't get set correctly or somehow an auto generated one gets used or something. Can you please check how you're creating user identifiers? 

We also moved servers and it took a while for all signals to catch up, so please double check again now that everything is running smoothly.

**Comment by SamSmallman** [comment] 2024-07-30 13:09
Just trying to dig into this and provide some help. Looking at telemetrydeck.json on the Android I can see that when setting testMode to true that is reflected in the JSON file like so:
... ,"isTestMode":true, ...
When setting testMode to false, "isTestMode" is not present. This seems to be different to the Swift SDK where "isTestMode" is present and would have a value of false if test mode is turned off.
Might it be that Android is correctly sending valid JSON but the server is not converting the absence of a value or even a null value to be false?

**Comment by FantaMagier** [comment] 2024-08-20 18:08
I wanted to ask about an update. Android still doesn't work despite the latest version :(

**Comment by kkostov** [comment] 2024-08-21 13:31
@FantaMagier just to make sure we're on the same page - Using version `0.6.0`, no signals from android devices are visible on the portal, in test mode or otherwise? This is also the case for the "Recent Signals" tab (Explore > Recent Signals)?

Could you share with us a complete logcat trace for all lines filtered with `D/TELEMETRYDECK` from the app start until some signals have been sent.

**Comment by FantaMagier** [comment] 2024-08-21 17:13
@kkostov 
Thanks for your reply. I tested a new TelemetryDeck project and everything worked as expected (recent signal & dashboard data). With my app project the recent signal was received but the dashboard doesn't work for Android requests. 


```
I/System.out( 7874): D/TELEMETRYDECK: Broadcasting 2 queued signals
I/System.out( 7874): 19:06:17.774 [DefaultDispatcher-worker-5] INFO io.ktor.client.HttpClient - REQUEST: https://nom.telemetrydeck.com/api/v1/apps/ID/signals/multiple/
I/System.out( 7874): METHOD: HttpMethod(value=POST)
I/System.out( 7874): COMMON HEADERS
I/System.out( 7874): -> Accept: application/json; application/json
I/System.out( 7874): -> Accept-Charset: UTF-8
I/System.out( 7874): CONTENT HEADERS
I/System.out( 7874): -> Content-Length: 1417
I/System.out( 7874): -> Content-Type: application/json
I/System.out( 7874): BODY Content-Type: application/json
I/System.out( 7874): BODY START
I/System.out( 7874): [{"receivedAt":"2024-08-21T17:06:08.307Z","appID":"ID","clientUser":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","sessionID":"9122cedc-ac61-41b9-af44-59c3a99be53d","type":"ANDROID SDK TEST\t2","payload":["dartVersion:3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on 'android_arm64'","telemetryClientVersion:Flutter 0.3.0","appVersion:2.2.1","buildNumber:82","systemVersion:Android SDK: 34 (14)","majorSystemVersion:14","majorMinorSystemVersion:14.0","locale:Deutsch (Deutschland)","brand:google","targetEnvironment:emu64a","modelName:sdk_gphone64_arm64 (sdk_gphone64_arm64)","architecture:aarch64","operatingSystem:Android"],"isTestMode":"false"},{"receivedAt":"2024-08-21T17:06:08.308Z","appID":"ID","clientUser":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","sessionID":"9122cedc-ac61-41b9-af44-59c3a99be53d","type":"App Start","payload":["dartVersion:3.5.0 (stable) (Tue Jul 30 02:17:59 2024 -0700) on 'android_arm64'","telemetryClientVersion:Flutter 0.3.0","FirstOpen:false","appVersion:2.2.1","buildNumber:82","systemVersion:Android SDK: 34 (14)","majorSystemVersion:14","majorMinorSystemVersion:14.0","locale:Deutsch (Deutschland)","brand:google","targetEnvironment:emu64a","modelName:sdk_gphone64_arm64 (sdk_gphone64_arm64)","architecture:aarch64","operatingSystem:Android"],"isTestMode":"false"}]
I/System.out( 7874): BODY END
D/TrafficStats( 7874): tagSocket(195) with statsTag=0xffffffff, statsUid=-1
D/EGL_emulation( 7874): app_time_stats: avg=33.83ms min=16.92ms max=50.39ms count=30
I/System.out( 7874): 19:06:17.898 [DefaultDispatcher-worker-7] INFO io.ktor.client.HttpClient - RESPONSE: 200 
I/System.out( 7874): METHOD: HttpMethod(value=POST)
I/System.out( 7874): FROM: https://nom.telemetrydeck.com/api/v1/apps/ID/signals/multiple/
I/System.out( 7874): COMMON HEADERS
I/System.out( 7874): -> access-control-allow-origin: *
I/System.out( 7874): -> content-length: 2
I/System.out( 7874): -> content-type: text/html; charset=utf-8
I/System.out( 7874): -> date: Wed, 21 Aug 2024 17:06:17 GMT
I/System.out( 7874): -> strict-transport-security: max-age=15724800; includeSubDomains
I/System.out( 7874): BODY Content-Type: text/html; charset=utf-8
I/System.out( 7874): BODY START
```

New Test Project:
![image](https://github.com/user-attachments/assets/ee97b6b2-c2be-4703-9b78-ea13aae08dc1)


Old Project:
![image](https://github.com/user-attachments/assets/17a5f155-dcaf-4b0a-88bb-07dadb8e4eff)
But recent Signal was recieved:
![image](https://github.com/user-attachments/assets/6572e66d-bb45-413e-8aae-50454bc37c5c)

**Comment by kkostov** [comment] 2024-08-23 14:52
The attribute indicating the OS sent out from the SDK on Android is `operatingSystem` and not `TelemetryDeck.Device.operatingSystem`, the Android SDK has not been migrated through the "Grand Rename" @winsmith

**Comment by kkostov** [comment] 2024-12-16 16:16
The Flutter SDK has introduced the "Grand Rename" adaption of signals which should significantly improve working with the dashboard. Please try updating the Flutter SDK to the latest version.

**Closed by kkostov** 2024-12-16 16:16 UTC
